# Generated by Django 3.0.4 on 2020-03-11 04:36

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Name does not allow special charecters', regex='^[\\w-]+$')])),
                ('title', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankref', models.CharField(max_length=100, verbose_name='Bank Reference')),
                ('ref1', models.CharField(max_length=100, verbose_name='Ref1')),
                ('ref2', models.CharField(max_length=100, verbose_name='Ref2')),
                ('qrid', models.CharField(max_length=100, verbose_name='QR id')),
                ('payername', models.CharField(max_length=100, verbose_name='Payer name')),
                ('payerbank', models.CharField(max_length=100, verbose_name='Payer Bank')),
                ('amount', models.FloatField(default=0, verbose_name='Amont')),
                ('fee', models.FloatField(default=0, verbose_name='Fee charge')),
                ('transdate', models.DateTimeField(verbose_name='Trans Date')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifies', to='notify.Bank', verbose_name='Bank')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
