# Generated by Django 3.0.4 on 2020-03-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0002_auto_20200311_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='notify',
            name='billno',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Biller number'),
        ),
        migrations.AddField(
            model_name='notify',
            name='resultcode',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Result Code'),
        ),
        migrations.AddField(
            model_name='notify',
            name='resultdesc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Result Describe'),
        ),
    ]
