# Generated by Django 3.0.4 on 2020-03-13 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0003_auto_20200313_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notify',
            old_name='billno',
            new_name='billerno',
        ),
    ]
